### PR TITLE
Feat/dao incubation schema fix

### LINKED ISSUE #44: No/Empty data is being sent on Attestation from Zenbit Badges Website
- It was working until `DAO Formation` event
- It's not working anymore after this event

### PR DESCRIPTION
**Pull request by Markkos89**
## Description

- dao incubation schema fix
- this closes #44

### CODE REVIEW

File: packages/nextjs/pages/api/userQuiz.ts [hunk 1]
```diff
@@ -21,16 +25,16 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse<
...
-          const result = await checkAnswer(req.body);
+        // if (req.body.eventType !== "4") {
+        const result = await checkAnswer(req.body);
 
-          res.status(200).json({ data: result, message: "Quiz answer checked successfully" });
-        } else {
-          // check correct secret word for event type LIVE EVENT
-          const result = await checkLiveEventAnswer(req.body);
+        res.status(200).json({ data: result, message: "Quiz answer checked successfully" });
+        // } else {
```
Comment (shyam-patel-kira) [inline packages/nextjs/pages/api/userQuiz.ts]: cleanup this if not required

**Review by shyam-patel-kira — APPROVED** [review]

**Review by HabacucMX — APPROVED** [review]
